name: ci

on:
  push:
    braches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login To Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push frontend image
        uses: docker/setup-buildx-action@v2
        with:
          context: frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
      -
        name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
      - 
        name: Build and push Mongo image
        run: docker pull mongo:4.2.0 && docker tag mongo:4.2.0 ${{ secrets.DOCKERHUB_USERNAME }}/mongo:latest
      
    
